#define MASTER_LEFT

#define USE_SERIAL_PD2

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 170
#define TAPPING_TOGGLE 1
#define IGNORE_MOD_TAP_INTERRUPT
#define TYPING_FORCE_HOLD
#define PERMISSIVE_HOLD
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
//#define NO_ACTION_MACRO
//#define NO_ACTION_FUNCTION
// Configure the OLED screen to reduce burn-in
//#define OLED_TIMEOUT 10000
//#define OLED_BRIGHTNESS 80
